version: "3.8"
services:
  # --- THE TRADING WAREHOUSE ---
  nio_postgres:
    image: postgres:15
    container_name: nio_postgres
    environment:
      - POSTGRES_USER=quant_user
      - POSTGRES_PASSWORD=quant_password
      - POSTGRES_DB=trading_warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- AIRFLOW DATABASE (Internal) ---
  airflow_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  # --- AIRFLOW WEBSERVER & SCHEDULER ---
  airflow:
    # image: apache/airflow:2.7.1-python3.10
    # user: root # Still need root for the JRE
    build: .
    depends_on:
      - airflow_db
      - nio_postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_db/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=nio_trading_project_secret_123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts # Maps your whole project folder # <-- THIS IS THE FIX. Added the './scripts'
    ports:
      - "8080:8080"
    # This simpler command ensures Airflow actually stays running and doesn't exit immediately
    command: bash -c "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true && (airflow scheduler & airflow webserver)"

volumes:
  postgres_data:
  airflow_db_data:
